#!/usr/bin/env bash
# Path to the /etc/passwd file
passwd_file="/etc/passwd"
# Use a while loop to read each line in the file
while IFS=: read -r username _ userid _ _ home_directory _; do
	echo "$username:$userid:$home_directory"
done < "$passwd_file"
