#!/usr/bin/env bash
# Path to the /etc/passwd file
passwd_file="/etc/passwd"
# Use a while loop to read each line in the file
while IFS=: read -r username password userid groupid useridinfo homedir cmdshell; do
    echo "The user $username is part of the $groupid gang, lives in $homedir and rides $cmdshell. $userid's place is protected by the passcode $password, more info about the user here: $useridinfo"
done < "$passwd_file"
